### ISSUE TITLE
What are the meanings of the 11 criteria in text evaluation data?

### ISSUE THREAD

**Issue by ychyhy** [C4AI/ArGPT#1]
This is a great job. But I have a small question.
What are the meanings of the 11 criteria in text evaluation data？
If I receive an answer, I would greatly appreciate it.

**Comment by victorhnr** [comment]
Hi @ychyhy! Thank you for asking. We have just updated the README with the meaning of the criteria

**Comment by ychyhy** [comment]
Thank you for the update! I appreciate you taking the time to clarify the meaning of the criteria in the README.
________________________________
发件人: Victor Hugo ***@***.***>
发送时间: 2024年4月8日 22:45
收件人: C4AI/ArGPT ***@***.***>
抄送: ychyhy ***@***.***>; Author ***@***.***>
主题: Re: [C4AI/ArGPT] What are the meanings of the 11 criteria in text evaluation data? (Issue #1)


Hi! Thank you for asking. We just updated the README with the meaning of the criteria

―
